### ISSUE TITLE
Feature Request: Encrypt admin token & SMTP credentials

### ISSUE THREAD

**Issue by Shadowpheonix** [hassio-addons/addon-bitwarden#10]
The "configs\hassio\addons\data\a0d7b954_bitwarden\config.json" file contains plain text account login data, such as the Admin token for Bitwarden and the SMTP username & password.

This presents a security risk (albeit a small one, if your server's file system is properly secured).

Encrypting this data would be more secure, and is therefore preferable - especially when dealing with a password storage database.

**Comment by frenck** [comment]
That file is not part of the add-on, but part of Bitwarden RS itself.
Add-ons wrap existing applications. Please create a feature request at Bitwarden RS.
