### ISSUE TITLE
 0.9.0 error when try upload file bigger than 10 mb 

### ISSUE THREAD

**Issue by shirou93** [hassio-addons/addon-bitwarden#106]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

Upload attachment bigger than 10mb (bitwarden can upload 100mb attachments)

## Actual behavior

error when try upload file bigger than 10 mb "2021/04/07 15:44:27 [error] 413#413: *25 client intended to send too large body: 13142859 bytes, "

## Steps to reproduce
Try upload attachment bigger than 10 mb
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Did you try the setting in the documentation?

https://github.com/hassio-addons/addon-bitwarden/blob/main/bitwarden/DOCS.md#option-request_size_limit

**Comment by shirou93** [comment]
@sinclairpaul  thanks work
