### ISSUE TITLE
add config to enable admin page und disable user registration

### ISSUE THREAD

**Issue by drummer3333** [hassio-addons/addon-bitwarden#109]
# Problem/Motivation

- after setting up the first user the User Registration is not needed anymore. bitwarden_rs registration can be disabled via env_var
- the admin panel is only availible if you set a token as env var.

## Expected behavior

Add config options to set the env vars.

https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-registration-of-new-users
https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-admin-page

**Comment by frenck** [comment]
Read the add-on installation instructions, as it the admin panel token is part of the installation process.
