### ISSUE TITLE
Have I Been Pwned API Key

### ISSUE THREAD

**Issue by mightymight88** [hassio-addons/addon-bitwarden#113]
# Problem/Motivation

> Wanting to use the Data Breach report but need valid Have I Been Pwned API key.

## Expected behavior

> I purchased the API key and expected a way to be able to insert it somewhere to use. Or even a way to follow the instructions, "Once you have the key, open your ./bwdata/env/golbal.override.env and REPLACE the placeholders value for globalSettnigs_hibpApiKey= with your purchased API key:"

## Actual behavior

> Haven't found a place in the addon settings or config files to add this API key.

## Steps to reproduce

> Install this addon, go to Tools > Data Breach Report > add your email address > Check Breaches > See message about needing API key.

## Proposed changes

> If this is even possible, maybe some documentation on how to add the API key?

**Comment by frenck** [comment]
You can set it in the admin panel:

![image](https://user-images.githubusercontent.com/195327/114919739-e737b400-9e28-11eb-82a0-2e739f69af96.png)
