### ISSUE TITLE
Unable to setup 2FA due to TZ mismatch

### ISSUE THREAD

**Issue by dpecos** [hassio-addons/addon-bitwarden#12]
# Problem/Motivation

I'm not able to setup 2FA using an authenticator app, getting as result `Invalid TOTP code`. My setup is already being served under a valid SSL domain.

After having a look to bitwarden_rs issues I found this ones: https://github.com/dani-garcia/bitwarden_rs/issues/466

And I think that's my issue: the docker container that homeassistant spins up does not have the proper timezone and thus my 2FA attempts fail.

Some commands in order to explain this better:

```
$ date                               
Sun 10 Nov 2019 09:41:36 PM CET                                    
$ sudo docker exec -it homeassistant date                                                                 
Sun Nov 10 21:43:24 CET 2019                                       
$ sudo docker exec -it addon_a0d7b954_bitwarden date
Sun Nov 10 20:44:13 UTC 2019  
```
HA's date and bitwardens are set to different TZ (HA has the correct TZ, which matches the first one from the host)

## Expected behavior

2FA to work

## Actual behavior

`Invalid TOTP code` error

## Steps to reproduce

Just try to enable 2FA from a different TZ than UTC

## Proposed changes

This plugin should honor HA's TZ when spinning up the container for Bitwarden

**Comment by sinclairpaul** [comment]
Can you confirm your OS? I would guess its HASSOS?

**Comment by dpecos** [comment]
The OS from the host is Arch, and I'm running hass.io within a docker container.

I can't tell if it's relevant or not, but based on the linked issue (https://github.com/dani-garcia/bitwarden_rs/issues/466) I would say it is.

And then, there is indeed a drift of 1 hour between bitwarden containter and the browser I'm using, because of the timezone different, which is not correct, because both boxes are sitting next to the other.

That being said, I'm not 100% confident that this would solve the issue, but at least, IMHO, points in the correct direction.

**Comment by sinclairpaul** [comment]
Perhaps you could confirm by matching the Timezone on your client device?

**Comment by sinclairpaul** [comment]
I cannot duplicate this, I still believe the issue is time drift between your server and device (Timezone differences should not impact this, it would be based on UTC).

![image](https://user-images.githubusercontent.com/24625998/68611477-3802ea80-0488-11ea-80db-63c22b5debe1.png)

$ date
Mon Nov 11 13:34:35 EST 2019

$ sudo docker exec -it addon_a0d7b954_bitwarden date
Mon Nov 11 18:34:41 UTC 2019

**Comment by dpecos** [comment]
I've been able to finally set it up after running `ntp` on the host machine, so I guess it was indeed a time drift.

Thx for your help and sorry for the misleading issue ¯\_(ツ)_/¯
