### ISSUE TITLE
admin page

### ISSUE THREAD

**Issue by darkh89** [hassio-addons/addon-bitwarden#120]
# Problem/Motivation

> (Why the issue was filed)
Not a problem, but there is a way to disable or enable admin page ?

## Expected behavior

I would like to have the possibility to activate or deactivate the /admin url from hassio.

**Comment by frenck** [comment]
See installation instructions.

**Comment by darkh89** [comment]
Great answer !

But nothing in your "installation instructions" to be able to disable admin url after bw configured.

**Comment by frenck** [comment]
That would be a feature request for the upstream project. Add-ons wrap existing software, we don't create it.
