### ISSUE TITLE
Logon from Windows app or Android app not possible

### ISSUE THREAD

**Issue by mkh595** [hassio-addons/addon-bitwarden#13]
I tested Bitwarden with account in cloud and it works from Web app, Chrome extension, Windows app and Android app.
I install Bitwarden addon in Hassio but I can logon only from Web-UI and Chrome extension. It is not possible logon from Windows or Android app. As URL I used IP of RPI https://192.168.1.14:7277

Error says "_There is problem connecting to the server_" or "_Failed to fetch_"
In the log appears:
```
[2019-11-22 11:04:26][rustls::msgs::handshake][WARN] Illegal SNI hostname received [49, 57, 50, 46, 49, 54, 56, 46, 49, 46, 49, 52]
```

**Comment by sinclairpaul** [comment]
Please ensure you connect with the name you setup for your certificate (i.e. https://192.168.1.14 will throw an error, which more than likely you are ignoring in the browser).

**Comment by mkh595** [comment]
Thank you for hint. When I use domain name, I can logon from Windows app but not from Android. I found that there is issue with Android app #https://github.com/bitwarden/mobile/issues/630
