### ISSUE TITLE
Expose admin page token, enable/disable in settings

### ISSUE THREAD

**Issue by Eeems** [hassio-addons/addon-bitwarden#151]
# Problem/Motivation

I'd like to manage enabling/disabling the admin page, as well as setting the admin token from hassio.

## Expected behavior

The addon configuration should allow toggling the admin page, as well as setting the admin token.

## Actual behavior

There is no current configuration for these items.

## Proposed changes

It looks like it should be fairly straightforward to implement by passing the environment variables to the container, or to just modify the config.json manually.

https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page
https://github.com/dani-garcia/vaultwarden/wiki/Disable-admin-token

**Comment by frenck** [comment]
I think disabling the admin token is a security concern, I'm not willing to add that.

Enabling/disabling the admin page: Sure, PRs are welcome.

**Comment by Eeems** [comment]
> I think disabling the admin token is a security concern, I'm not willing to add that.

Fair enough. 

> Enabling/disabling the admin page: Sure, PRs are welcome.

If I can get the time I'll try to. No promises though. I might add other things like disabling user registration as well if I get the time.

**Comment by frenck** [comment]
Disabling user registration is possible from the admin page, there is no need to add configuration for that in the add-on.

**Comment by Eeems** [comment]
> Disabling user registration is possible from the admin page, there is no need to add configuration for that in the add-on.

Fair enough
