### ISSUE TITLE
Can't open file attachments - 

### ISSUE THREAD

**Issue by madmic1314** [hassio-addons/addon-bitwarden#17]
# Problem/Motivation

Can't open attachments. Have an error

## Expected behavior

Open attachments, download file 

## Actual behavior

In desktop app spinning icon. Can see an error in Developer Console

## Steps to reproduce

Create a new item (or use an old one with an attachment). Attempt to open attachment. Open Developer Console and you'll see when opening or editing an item it references https://[url of bitwarden server]:7272/ ....    instead when trying to open attachments its: https://localhost/attachments/... which is incorrect. Have attached images of both here:

![Bitwarden_Error](https://user-images.githubusercontent.com/53381142/72567375-b37c8000-38ad-11ea-92c8-9f9c0101748e.png)

![Bitwarden_Working](https://user-images.githubusercontent.com/53381142/72567388-b9726100-38ad-11ea-9df7-1b81431ff4ed.png)

## Proposed changes

https://github.com/bitwarden/server/issues/264 implies this is an issue with the ./bwdata/env/global.override.env file. Correct the entries here.

**Comment by sinclairpaul** [comment]
You can update this via the admin panel, please remember to include the port:

![image](https://user-images.githubusercontent.com/24625998/72568959-3d652280-3887-11ea-804c-b0eaf448160b.png)

**Comment by madmic1314** [comment]
Thanks - had found that and made the change. All working now.

I'm positive this has always been the default localhost but attachments had been working before. Either way, all good and working.

**Comment by sinclairpaul** [comment]
@madmic1314 The last release added nginx to the build so we could get websockets working correctly, its likely that it may have introduced the issue.
