### ISSUE TITLE
Missing option to add addon to sidebar panel

### ISSUE THREAD

**Issue by adrianmo** [hassio-addons/addon-bitwarden#186]
# Problem/Motivation

After installing the addon, I'm missing the option of adding the addon to the sidebar. This would make the addon much more accessible. 

## Expected behavior

The addon would allow users to show the addon in the sidebar menu for fast access.

![image](https://user-images.githubusercontent.com/3786750/145978805-b286100f-f9ab-4e8e-9452-a229c1ec2eab.png)

## Actual behavior

The "Show in sidebar" option is not currently available.

![image](https://user-images.githubusercontent.com/3786750/145979000-748788d3-9e04-4966-85bd-58005ce46105.png)

## Steps to reproduce

Install the addon and then go to the addon info page (or click [![Open your Home Assistant instance and show the dashboard of a Supervisor add-on.](https://my.home-assistant.io/badges/supervisor_addon.svg)](https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_bitwarden)).

## Proposed changes

I'm not not 100% sure, but maybe just adding the `panel_icon` to the `config.yaml` file would make the option available. If somebody can confirm that, I can quickly submit a PR with the change.

**Comment by frenck** [comment]
This is not a bug, but simply not possible with this add-on.

Also documented it:

![image](https://user-images.githubusercontent.com/195327/145982206-58402e55-bd83-41b0-91b0-02e2c0f6d03f.png)


<https://github.com/hassio-addons/addon-bitwarden/blob/main/bitwarden/DOCS.md#known-issues-and-limitations>
