### ISSUE TITLE
Token ADmin

### ISSUE THREAD

**Issue by gastonMM** [hassio-addons/addon-bitwarden#196]
# Problem/Motivation

the token does not appear in the log
## Expected behavior

display the token or link to retrieve it

## Actual behavior

https://prnt.sc/o0dMstUe41b7

## Steps to reproduce

Restart Vaultwarden

**Comment by frenck** [comment]
As per documentation:

> The admin/token in the logs is only shown until it is saved or changed

**Comment by gastonMM** [comment]
After that, can't recover? thanks

**Comment by frenck** [comment]
No, there is no recovery from that.
