### ISSUE TITLE
Access from nabucasa.

### ISSUE THREAD

**Issue by abrahamfa** [hassio-addons/addon-bitwarden#197]
# Problem/Motivation

>From nabucasa I cannot access Vaultwarden and from the local ip I can access but my browser says that the site is insecure.

## Expected behavior

> Being able to access Vaultwarden even by opening router ports.

## actual behavior

> I can access Home Assistant and from nabucasa I can access all my addons except Vaultwarden

## Steps to play

> I have port 7277 open on my router but I don't know what else I can do. My browser says that the site is not secure from the local ip. I have tried copying the fullchain.pem and privkey.pem files from the .cloud folder that nabucasa creates and I don't get a good result. I have also tried to create my own ssl with duckdns and Let's Encrypt but I get the same results: Locally the site is not secure and from nabucasa I cannot access it.

I don't know if this happens to someone else and maybe it's possible that I have a bad configuration in my router. I do not consider the duckdns option because my router does not have nat loopback and in general I have good results with nabucasa.

Thanks!

**Comment by frenck** [comment]
As per documentation of this add-on:

![image](https://user-images.githubusercontent.com/195327/155888446-cbd12cdb-2a01-4f4c-a5e0-3b13b21d77ef.png)

Ref: <https://github.com/hassio-addons/addon-bitwarden/blob/main/bitwarden/DOCS.md#known-issues-and-limitations>
