### ISSUE TITLE
Struggling to get Vaultwarden addon to work with external URL (DuckDNS)

### ISSUE THREAD

**Issue by LoganJFisher** [hassio-addons/addon-bitwarden#198]
Vaultwarden is accessible via my local IP and the port 7277, but when I try to access it via https://[name of my Duck DNS].DuckDNS.org:7277, nothing loads.

NGINX and DuckDNS w/ Let's Encrypt are set up and working just fine. Both of those and Vaultwarden are configured with their certfile as fullchain.pem and their keyfile at privkey.pem

In the Vaultwarden admin (accessed locally, obviously), I have changed the Domain URL to my DuckDNS URL.

Vaultwarden is set to the default port 7277. NGINX is set to its two default ports of 443 and 80.

In the Vaultwarden Admin diagnostics under "Domain configuration", it says "No Match" in a red box and "HTTPS" in a green box.

I'm stumped and need help. Please be patient with me though - I really don't understand much about computer networking. I'm just good at following instructions.

**Comment by pertakman** [comment]
Have you opened up port 7277 on your router?

Cheers, Per

**Comment by LoganJFisher** [comment]
Ah, you see. I'm what we in the business call "a moron".

No, I did not open port 7277. It works perfectly now. Thanks.

**Comment by pertakman** [comment]
You're welcome! Let me know if you, like me, struggle with the settings to setup email with GMail.
