### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by DarrenRatcliffe** [hassio-addons/addon-bitwarden#2]
# Problem/Motivation

Can't create user in the Bitwarden UI

## Expected behavior

User to be created when you hit the submit button on the create user form

## Actual behavior

Nothing, I click submit and nothing happens, there are no logs generated so can't really offer up more information

## Steps to reproduce

Deploy add on as described, go to initial log on screen, go to create user and attempt to create user

## Proposed changes

None as I can't fathom why it isn't working

**Comment by timmo001** [comment]
Are you using chrome and not using SSL? Take a look at the known limitations:

https://github.com/hassio-addons/addon-bitwarden#known-issues-and-limitations

You will have to enable SSL for the login/signup prompt to work.

**Comment by DarrenRatcliffe** [comment]
Yes this is the issue, enabled ssl and it works now
