### ISSUE TITLE
Downloads of attachments are not working

### ISSUE THREAD

**Issue by hrzlgnm** [hassio-addons/addon-bitwarden#201]
# Problem/Motivation
> I've added an attachment to a login account successfully, when i try to download it, an error happens.
> Setup was: vaultwarden SSL enabled and port exposed directly

## Expected behavior

> The attached file downloads successfully.

## Actual behavior

> I get an error message that something went wrong.
> The download works fine, if SSL is disabled in the addon and another means of SSL termination like Ngninx Proxy Manager is used

## Steps to reproduce
> Install Bitwaden(Vaultwarden) addon, set it up with SSL enabled add port 7277
> Create a login, attach a file to it
> Try to download that file again

## Proposed changes

> In the develop console of my browser i could see, that the download is tried with an http:// url, even though i've set to connect via a https:// url.
> As this happens regardless of the used app/browser i guess it's a server side thing.

**Comment by hrzlgnm** [comment]
Solved the issue by not exposing the https port of bitwarden directly, but rather using nginx proxy manager to do the ssl offload

**Comment by sinclairpaul** [comment]
Closing as then it's likely configuration which can be found in the VaultWarden documentation,.
