### ISSUE TITLE
0.17.0 [DEPRECATED]: `SMTP_SSL`

### ISSUE THREAD

**Issue by shirou93** [hassio-addons/addon-bitwarden#210]
Logs when start addon:

[DEPRECATED]: `SMTP_SSL` or `SMTP_EXPLICIT_TLS` is set. Please use `SMTP_SECURITY` instead.

**Comment by frenck** [comment]
The add-on doesn't handle these, Vaultwarden itself does that. From an add-on perspective there is not much we can do.

Have you tried reviewing/resaving your configuration from the Vaultwarden admin panel?

**Comment by shirou93** [comment]
Resave config on admin panel solve issue. Thanks
