### ISSUE TITLE
Unable to start bitwarden after installation

### ISSUE THREAD

**Issue by fireheadman** [hassio-addons/addon-bitwarden#224]
The configuration tab has nothing in it...
I installed the addon, then tried to start it.

I see this in the logs tab
![image](https://user-images.githubusercontent.com/19847195/205103120-457164b6-727e-4bb0-8541-37ceca3a47f0.png)

**Comment by fireheadman** [comment]
```fireheadman@hassio:/usr/share/hassio/addons/data/a0xxxx_bitwarden$ sudo cat options.json
[sudo] password for fireheadman:
{
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "ssl": true
fireheadman@lancelot:/usr/share/hassio/addons/data/a0d7b954_bitwarden$ sudo cat options.json
[sudo] password for fireheadman:
{
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "ssl": true
```

**Comment by kaybeebee** [comment]
> ```
> fireheadman@hassio:/usr/share/hassio/addons/data/a0xxxx_bitwarden$ sudo cat options.json
> [sudo] password for fireheadman:
> {
>   "certfile": "fullchain.pem",
>   "keyfile": "privkey.pem",
>   "ssl": true
> ```

Had the same problem. Just use the standard config from the documentation as a start:
```
log_level: info
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
request_size_limit: 10485760
```
Source: https://github.com/hassio-addons/addon-bitwarden/blob/main/bitwarden/DOCS.md

**Comment by fireheadman** [comment]
It finally worked
