### ISSUE TITLE
email 2fa is disabled

### ISSUE THREAD

**Issue by cablesky** [hassio-addons/addon-bitwarden#228]
Hi!
How (and where) can I enable the "email 2fa is disabled" feature?
I keep getting the error "email 2fa is disabled"...

**Comment by frenck** [comment]
You can set this kind of thing up in the admin panel.

e.g., `http://home-assistant.local:7277/admin` (adopt it to the location for your instance).

../Frenck

**Comment by cablesky** [comment]
It's not what I mean. If you want to activate this function, the error message "email 2fa is disabled" is displayed.

**Comment by cablesky** [comment]
Thank you!

**Comment by cablesky** [comment]
One Question: How to change the confirmation url in the mail from localhost..... to <own_url>?

**Comment by frenck** [comment]
You can configure that in the same admin interface; it is the domain setting.
