### ISSUE TITLE
documentation to setup SSL

### ISSUE THREAD

**Issue by andyfitz** [hassio-addons/addon-bitwarden#235]
# Problem/Motivation

The web UI doesnt work in most browsers without SSL enabled 

## Expected behavior
To be able to create bitwarden accounts and login 

## Actual behavior

Users cannot login in modern browsers without HTTPS

## Steps to reproduce

Standard install 

## Proposed changes

Simple documentation to install in a homeassistant or hassos environment

**Comment by frenck** [comment]
There are million ways to do that, whatever your preferred choice of handling SSL, the add-on will accept the certificates in the addon configuration (which are documented).

I cannot help you with (or recommend any way) to set up SSL.

There are to many of those around.

../Frenck
