### ISSUE TITLE
"Open Web UI" doesn't load "ERR_CONNECTION_TIMED_OUT"

### ISSUE THREAD

**Issue by shrowner** [hassio-addons/addon-bitwarden#239]
# Problem/Motivation

"Open Web UI" doesn't load "ERR_CONNECTION_TIMED_OUT".  First time install and have never been able to access the UI.

Local IP and remote produce the same behavior.  Home Assistant is exposed via CloudFlare: https://www.youtube.com/watch?v=xXAwT9N-7Hw

## Expected behavior

Load login page

## Actual behavior

ERR_CONNECTION_TIMED_OUT
<img width="873" alt="image" src="https://user-images.githubusercontent.com/19720088/212192880-10c9b04a-83ce-40d7-88e2-43316d8705a6.png">

## Steps to reproduce

Config

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/19720088/212193055-3d278ece-59f1-43d3-893c-c9d275a7e289.png">

Logs:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Vaultwarden (Bitwarden)
 Open source password management solution
-----------------------------------------------------------
 Add-on version: 0.18.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.12.1
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[14:52:20] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun bitwarden (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:52:20] INFO: 
[14:52:20] INFO: 
[14:52:20] INFO: READ THIS CAREFULLY! READ THIS CAREFULLY!
[14:52:20] INFO: 
[14:52:20] INFO: 
[14:52:20] INFO: This is your temporary random admin token/password!
[14:52:20] INFO: 
[14:52:20] INFO: REMOVED
[14:52:20] INFO: 
[14:52:20] INFO: Be sure to change it in the admin panel, as soon as possible.
[14:52:20] INFO: 
[14:52:20] INFO: After you have changed ANY setting in the admin panel,
[14:52:20] INFO: the add-on will NOT generate a new token on each start
[14:52:20] INFO: and stops showing this message.
[14:52:20] INFO: 
[14:52:20] INFO: Starting the Vaultwarden server...
/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                           Version 1.26.0                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/
[INFO] No .env file found.
[2023-01-12 14:52:20.332][vaultwarden::api::notifications][INFO] Starting WebSockets server on 0.0.0.0:8080
[2023-01-12 14:52:20.334][start][INFO] Rocket has launched from http://127.0.0.1:80
[14:52:20] INFO: Starting NGinx...

**Comment by IceBotYT** [comment]
I'm having this issue too

**Comment by shrowner** [comment]
Added IP and port to "Additional Hosts" in Cloudflared add-on

![image](https://user-images.githubusercontent.com/19720088/214372805-8144d6ca-e530-4e57-bda6-00f5a1c6d58f.png)
