### ISSUE TITLE
Unable to add U2F authentication

### ISSUE THREAD

**Issue by nonsleepr** [hassio-addons/addon-bitwarden#24]
# Problem/Motivation

I'm unable to add U2F authentication to my account.

## Expected behavior

I should be able to add FIDO U2F Security Key to my account.

## Actual behavior

Getting an error:
> `DOMAIN` environment variable is not set. U2F disabled

## Steps to reproduce

Go to "Settings" -> "Two Factor Authentication", select "FIDO U2F Security Key".

## Proposed changes

As per [Bitwarden_rs documentation](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-U2F-authentication), add an option to set `DOMAIN` environment variable.

**Comment by frenck** [comment]
You can set that via the admin panel on e.g.: `http://hassio.local:7277/admin`

See the documentation of the add-on for more information on that panel.
