### ISSUE TITLE
Web sockets URLs and port forwarding?

### ISSUE THREAD

**Issue by silverl** [hassio-addons/addon-bitwarden#242]
# Problem/Motivation

I learned [on a Reddit thread](https://www.reddit.com/r/vaultwarden/comments/1026ty4/comment/j2taamc/) that Vaultwarden supports websockets for providing clients a way to get updated in near real-time.

[Vaultwarden notes on websockets support here.](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-WebSocket-notifications)

I use nginx-proxy-manager to manage my TLS certificates in a similar way that the participants in the thread are discussing.

Looks like the Vaultwarden docker would need to listen on 2 more ports to enable the websockets support? I'm not totally sure. In the reddit thread, they're using nginx-proxy-manager to configure and enable websockets on ports 3012 and 80. I imagine we'd need to remap at least port 80 to something else for Home Assistant support.

## Expected behavior

Websockets from BitWarden clients should be able to register with the Vaultwarden server.

## Actual behavior

I think websockets can't work unless we expose these other ports somehow.

## Steps to reproduce

N/A

## Proposed changes

Modify docker to expose these other ports? Not sure, not a docker expert.

**Comment by sinclairpaul** [comment]
Websockets support was already configured, by the nginx component running in the addon.

If there is an issue, can you share the browser dev tools output showing the failure (the article you linked also shows how to test it).

**Comment by silverl** [comment]
Oh, that's good news. I'm pretty new to BitWarden and I was trying to figure out why the Windows thick client can authenticate yet fails to load any records. A few rabbit holes led me down the websockets route, and when I didn't see ports being forwarded like in Vaultwarden's documentation, I assumed it hadn't been implemented yet in the HASS Add-On.

Thanks for clearing that up.

**Comment by silverl** [comment]
FWIW I'm getting 404s when viewing the dev tools pane in the native Windows client (which looks to be Electron-based or some similar chromium-engine-based environment).

For example, requests to /sync?excludeDomains=true return HTTP 404 for some reason.

**Comment by silverl** [comment]
I may have solved that issue for myself. I was running the Windows Store version of BitWarden. I just downloaded the Dec portable release [from here](https://github.com/bitwarden/clients/releases/tag/desktop-v2022.12.0) and that seems to be more compatible with the Dec Vaultwarden HASS release.
