### ISSUE TITLE
Add option to disable admin page

### ISSUE THREAD

**Issue by swiewiora** [hassio-addons/addon-bitwarden#248]
My bad, I didn't notice there already was an issue for it, can you please remove it?

# Problem/Motivation

> If a user chooses to expose Vaultwarden to Internet, admin page can be accessed with it. It seems that the access to it is less secure than to the Vault as there is no 2FA and no notifications are sent on failed login attempts. Admin page is used mainly in the initial configuration. Vaultwarden allows user to enable and disable admin page: https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page

## Expected behavior

> addon-bitwarden allows disabling and re-enabling admin panel for increased security

## Actual behavior

> Admin page is always available, there is no way to disable it.

## Steps to reproduce

> go to https://your.domain:7277/admin

## Proposed changes

> Add parameter that allows disabling admin page:
> Option: `admin_panel`
> - `true`: enable admin panel, default
> - `false`: disable admin panel

**Comment by frenck** [comment]
You closed it as it isn't relevant anymore @swiewiora?

**Comment by swiewiora** [comment]
@frenck I closed it as duplicate of https://github.com/hassio-addons/addon-bitwarden/issues/120 and https://github.com/hassio-addons/addon-bitwarden/issues/151
