### ISSUE TITLE
can't install latest update 0.19.4

### ISSUE THREAD

**Issue by jdumeez** [hassio-addons/addon-bitwarden#267]
# Problem/Motivation

When trying to update from 0.19.3 to 0.19.4 an error is thrown:
 
_Can't install ghcr.io/hassio-addons/bitwarden/amd64:0.19.4: 500 Server Error for http+docker://localhost/v1.42/images/ghcr.io/hassio-addons/bitwarden/amd64:0.19.4/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")_

![image](https://github.com/hassio-addons/addon-bitwarden/assets/87583037/7a83137f-85b6-43a0-bcd5-977ba20549b9)

Currently on the vary latest version of home assistant running other official and community add-ons: 
Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Frontend 20230503.3 - latest

**Comment by frenck** [comment]
> `readlink /mnt/data/docker/overlay2/l: invalid argument`

This is not an add-on issue, therefore closing it. 
Please report your issue with the Home Assistant Supervisor project instead.

../Frenck
