### ISSUE TITLE
Recover or force admin token

### ISSUE THREAD

**Issue by Ulrar** [hassio-addons/addon-bitwarden#28]
Hi,

Is there a way to force the admin token or recover it ?
I didn't save it correctly on first startup and it disappeared from the logs very quickly
. I tried portainer but it doesn't seem to want to work on my pi2 (it can't connect to /var/run/docker.sock and I couldn't find anything useful about it online) so I don't see any way of reading the config file in data.

Thank you

**Comment by madmic1314** [comment]
Does it not show up on every boot of the container? Give that a try. Have you got access to all the items? If you have them you can export them, create a new container and then re-import

**Comment by Ulrar** [comment]
It stops showing if you make any changes in the interface, so no
unfortunately it doesn't anymore.
I do have access, I'll do that, I was just wondering if there's a way

**Comment by frenck** [comment]
There is no way to recover it, which is the whole point.
The documentation has been clear about it.
