### ISSUE TITLE
Config Enabling Mobile Client push notification

### ISSUE THREAD

**Issue by svenrobbie** [hassio-addons/addon-bitwarden#283]
# Problem/Motivation

> Config Enabling Mobile Client push notification

## Expected behavior

> Enable Mobile Client push notification in config file and have it auto sync.

## Actual behavior

> It's not possible to enable the Mobile Client push notification true a change in the config file. if this is done true the config Supervisor
gives an error.

## Steps to reproduce

> Add:     environment:
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=
      - PUSH_INSTALLATION_KEY= 
      
  to config.

## Proposed changes

> Add the Enabling Mobile Client push notification function as a config file option.

**Comment by frenck** [comment]
This can be set in the admin page of vaultwarden, right?

I'm not sure why we should add environment variables for that?

../Frenck

**Comment by svenrobbie** [comment]
Nope, it's in the read-only section of the config....

**Comment by frenck** [comment]
In that case, please open a feature request with Vaultwarden. I'm not planning on adding features to set env variables. I think it is really confusing to have multiple ways to handle things.

../Frenck
