### ISSUE TITLE
Option to specify a database url

### ISSUE THREAD

**Issue by popoviciri** [hassio-addons/addon-bitwarden#285]
# Problem/Motivation

> Recently, I migrated from a docker setup of home assistant to haos. I currently also use the vaultwarden image with a mariadb database and wish to switch to this addon. However this addon has no option to use a different database than the default sqlite. 

## Expected behavior

> Ideally the user could chose which database to use.

## Actual behavior

> Currently, only default db file `data/sqlite3` file can be used with this addon. Vaultwarden can however work with for example core-mariadb addon. The `database_url` cannot be set in Bitwarden's admin panel but only as an environment variable at startup.

## Steps to reproduce

> n/a

## Proposed changes

> I have prepared a PR to add this `unused databse_url option` which I tested on a local instance. Would the devs of this repo be willing to consider it? I do not wish to pollute this repository otherwise.
I am aware there are other issues related with the subject, but are stale and the proposed changes were just requests of exposing the environment variables supported by vaultwarden which are different than what I'm proposing.

Thanks very much for your consideration.
Cheers!

**Comment by frenck** [comment]
This is not in scope for add-ons. If you need this kind of functionality, then this add-on is not for you. You should look into using Docker/container installation instead.

../Frenck

**Comment by popoviciri** [comment]
I just reached out before submitting a PR, following your `contributing` guideline. But I get the codeowner's position, although I respectfully disagree. Personally I already use this addon with core-mariadb, so is working for me. Cheers and thanks for all the work!
