### ISSUE TITLE
Bitwarden android client not connecting 

### ISSUE THREAD

**Issue by rolandsteinmeyer** [hassio-addons/addon-bitwarden#291]
# Problem/Motivation

I have set up vaultwarden addon and want to use it only from my internal network or via VPN access. As there is no simple way to get bitwarden client for android to work without certificate or with a self signed certificate I also use home assistant duckdns integration to create a dns entry and a letsencrypt certificate **for the internal IPv4 adress of home assistant** (192.168.X.X).  

If a use a browser to access https://myserver.duckdns.org:7277 everything works just fine (no certifiacte errors etc). Bitwarden for MacOS / Windows and Browser Plugins also work.

My problem is Bitwarden Android client. It is also set to "sef hosted", server URL is set to https://myserver.duckdns.org:7277
But it won't connect and gives a misleading error "unable to resolve hostname myserver.duckdns.org".

After trying many things to resolve this I noticed I can connect to vaultwarden from Bitwarden Android Client when I am using a VPN connection to my local network that is ipv4 only. So this seems IPv6 releated. DuckDNS entry and letsencrypt certificate are IPv4 only.

## Expected behavior

Local connection to vaultwarden should work for all bitwarden implementations.

## Actual behavior

Bitwarden for Android fails to connect on local network. Workaround is to switch of WLAN Access and connecting via mobile data and VPN which forces IPv4.

## Steps to reproduce

see above

## Proposed changes

Is there a way to disable ipv6 for vaultwarden addon without disabling ipv6 for the complete home assistant installation (because Matter depends on IPV6) ?

**Comment by screwzloose** [comment]
I have almost the exact same situation, yet I'm having the issue on the iOS app. Similar setup, self-hosted via Home Assistant. Using DuckDNS for certs, HAProxy via pfSense. I can access from macOS/Windows browsers, however, as of what I think to be a recent update I'm not longer able to login from the iOS app. 

This wasn't immediately obvious until I attempted to setup the Bitwarden iOS app on another iPhone. I then tried logging out on my iPhone, but couldn't log back in. However, when I revert to cellular data and VPN back in Wireguard, I'm able to log back into Bitwarden via the iOS app. 

Nothing changed in my environment. This may, or may not be related, but very similar situation.

**Comment by rolandsteinmeyer** [comment]
ping

**Comment by rolandsteinmeyer** [comment]
ping

**Comment by rolandsteinmeyer** [comment]
ping
