### ISSUE TITLE
ssl cert/key file

### ISSUE THREAD

**Issue by dvz92** [hassio-addons/addon-bitwarden#294]
The latest nginx proxy manager doesn’t output the cert/key files into /ssl/folder.  I have to update these files manually(download from npm then copy to ssl folder). Is there anyway to change the default setting?

**Comment by renaiku** [comment]
Same.

It's probably related to https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/518

**Comment by frenck** [comment]
The nginx proxy manager is a rever proxy. Please use it as such (as a reverse proxy) and not as an SSL certificate generator.

If you are not interested in running a reverse proxy, but only generating certificate: There is an Let's Encrypt add-on that is maintained by the Home Assistant team. The goal of that add-on is to generate certificates.

../Frenck

**Comment by renaiku** [comment]
Don't know why but I just started once the let's encrypt addon (it was stopped) and now everything works again. The let's encrypt addon stopped itself and the logs doesn't show any errors so I guess it's working as intended.

**Comment by deam0n** [comment]
> The nginx proxy manager is a rever proxy. Please use it as such (as a reverse proxy) and not as an SSL certificate generator.
> 
> If you are not interested in running a reverse proxy, but only generating certificate: There is an Let's Encrypt add-on that is maintained by the Home Assistant team. The goal of that add-on is to generate certificates.
> 
> ../Frenck

yes, but If we're creating an SSL NPM with NgingxProxyManager, and something else (Adguard in this case) needs access to those certificates how to do it?

**Comment by padzero-test** [comment]
Hey, thanks for the advice on handling SSL certificates with two add-ons. Quick thing though, wouldn't using NginxProxyManager alone do the trick for us? I'm a bit concerned about complicating things with two add-ons. More moving parts mean more hassle and a higher risk, right? Just wondering if there's something specific about NginxProxyManager that makes it less ideal in our case. Cheers!
