### ISSUE TITLE
[Feature Request] Add configuration options for Mobile Client push service

### ISSUE THREAD

**Issue by martymarty004** [hassio-addons/addon-bitwarden#298]
# Problem/Motivation

Since version `v1.29.0` of Vaultwarden, it's possible to enable Mobile Client push notifications to allow logins from registered devices, and since version `v1.30.2` it's also possible to set the Data Region (US or EU). 
These are considered as Read-Only config in the admin page (because they require a restart to be set), so you are not able to configure them through the Web UI.

## Expected behavior

We should be able to set the following environment variables through the Configuration page of the add-on itself:

```txt
- PUSH_ENABLED=true                # Could be linked to a simple Bool switch
- PUSH_INSTALLATION_ID=            # Required string
- PUSH_INSTALLATION_KEY=           # Required string

- PUSH_RELAY_URI=https://push.bitwarden.eu                   # Optional, needed for EU region selection (Could be linked to a simple Bool switch)
- PUSH_IDENTITY_URI=https://identity.bitwarden.eu            # Could be linked to previous variable
```

If `PUSH_RELAY_URI` and `PUSH_IDENTITY_URI` are not provided, the config defaults to US automatically, as you can see in the relevant [PR](https://github.com/dani-garcia/vaultwarden/pull/3752/files)

## Actual behavior

At the moment, it is not possible to set these environment variables easily.
The only way to do that would be by manually editing the configuration file stored in the add-on data folder 
(which obviously doesn't persist after an update of the add-on).

## Steps to reproduce

N/A

## Proposed changes

Add the possibility to set these environment variables directly from the Add-on config 
(they could be easily exported to the container within the [run script](https://github.com/hassio-addons/addon-bitwarden/blob/main/bitwarden/rootfs/etc/s6-overlay/s6-rc.d/vaultwarden/run)).
Also, this new feature doesn't require any special port configuration, as every request goes through the main service port.

Everything I said is well documented in [Vaultwarden Wiki](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Mobile-Client-push-notification)

**Comment by frenck** [comment]
Closing as this is not an issue, but an feature request.

There is a discussion here: <https://github.com/hassio-addons/addon-bitwarden/discussions/279>

../Frenck
