### ISSUE TITLE
Restore database

### ISSUE THREAD

**Issue by florianfish** [hassio-addons/addon-bitwarden#303]
Hello,

How Can i restore a dump from another instance of vaultwarden ?

**Comment by Alfy1080** [comment]
I am also interested in this. I want to migrate from "zzz_archived - Vaultwarden" to this addon and I would like to migrate everything without requiring all users to re-register new accounts.

**Comment by frenck** [comment]
Use the Home Assistant backup feature.
You can restore full backups or backups of specific add-ons.

This is built-in functionality of Home Assistant itself.

../Frenck
