### ISSUE TITLE
Allow configuration for Push Notification parameters

### ISSUE THREAD

**Issue by markusmauch** [hassio-addons/addon-bitwarden#306]
# Problem/Motivation

Vaultwarden allows to set up Push Notification to send authentication requests from the web extension to the mobile app in order to use biometric authentication. The respective settings can be provided via environment variables:

PUSH_ENABLED=true
PUSH_INSTALLATION_ID=....
PUSH_INSTALLATION_KEY=....
PUSH_RELAY_BASE_URI=https://push.bitwarden.com

I tried to edit the config.json in the data directory of the addon accordingly and was able to set up Push Notifications. So it's just a matter of adding the settings in the addon configuration and start the vaultwarden container with theses additional env variables.

See also here:
https://2nistech.world/vaultwarden-activate-push-notification-for-mobile-devices/
https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Mobile-Client-push-notification

## Expected behavior

It should be possible to specify push notification settings in configuration of the addon

## Actual behavior

It is not possible to specify push notification settings in configuration of the addon

**Comment by pmetzke** [comment]
@markusmauch - thanks for testing to see if this would work!

It would be awesome to get these settings in the addon configuration.

**Comment by Salvora** [comment]
Also, waiting for this.
Additionally, if we can define environment variables. It is also possible to use MySQL or MariaDB as backend.
https://github.com/dani-garcia/vaultwarden/wiki/Using-the-MariaDB-%28MySQL%29-Backend

**Comment by dewet22** [comment]
Another 2p: I'd like to set the `DOMAIN` variable to enable [U2F / FIDO2 WebAuthn](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-U2F-%28and-FIDO2-WebAuthn%29-authentication).

**Comment by cuza** [comment]
@dewet22

> Another 2p: I'd like to set the `DOMAIN` variable to enable [U2F / FIDO2 WebAuthn](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-U2F-%28and-FIDO2-WebAuthn%29-authentication).

You can set that in the vaultwarden admin page (/admin) and use U2F / FIDO2 WebAuthn without problems

**Comment by dewet22** [comment]
> You can set that in the vaultwarden admin page (/admin) and use U2F / FIDO2 WebAuthn without problems

So odd! I don't remember seeing that at all. I ended up hosting vaultwarden on my homelab instead where I have better storage protection / backups anyway, but thanks for the tip!

**Comment by neckaros** [comment]
> # Problem/Motivation
> Vaultwarden allows to set up Push Notification to send authentication requests from the web extension to the mobile app in order to use biometric authentication. The respective settings can be provided via environment variables:
> 
> PUSH_ENABLED=true PUSH_INSTALLATION_ID=.... PUSH_INSTALLATION_KEY=.... PUSH_RELAY_BASE_URI=https://push.bitwarden.com
> 
> I tried to edit the config.json in the data directory of the addon accordingly and was able to set up Push Notifications. So it's just a matter of adding the settings in the addon configuration and start the vaultwarden container with theses additional env variables.
> 
> See also here: https://2nistech.world/vaultwarden-activate-push-notification-for-mobile-devices/ https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Mobile-Client-push-notification
> 
> ## Expected behavior
> It should be possible to specify push notification settings in configuration of the addon
> 
> ## Actual behavior
> It is not possible to specify push notification settings in configuration of the addon
> 
> ## Steps to reproduce
> ## Proposed changes

You mean editing the config.yaml on this repo or you did a modification on your installation.
First time looking at a HA addon but i think that indeed what should be done. Can you send a merge request if you successfully did it?

**Comment by StrausFuenf** [comment]
> > # Problem/Motivation
> > Vaultwarden allows to set up Push Notification to send authentication requests from the web extension to the mobile app in order to use biometric authentication. The respective settings can be provided via environment variables:
> > PUSH_ENABLED=true PUSH_INSTALLATION_ID=.... PUSH_INSTALLATION_KEY=.... PUSH_RELAY_BASE_URI=https://push.bitwarden.com
> > I tried to edit the config.json in the data directory of the addon accordingly and was able to set up Push Notifications. So it's just a matter of adding the settings in the addon configuration and start the vaultwarden container with theses additional env variables.
> > See also here: https://2nistech.world/vaultwarden-activate-push-notification-for-mobile-devices/ https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Mobile-Client-push-notification
> > ## Expected behavior
> > It should be possible to specify push notification settings in configuration of the addon
> > ## Actual behavior
> > It is not possible to specify push notification settings in configuration of the addon
> > ## Steps to reproduce
> > ## Proposed changes
> 
> You mean editing the config**.yaml** on this repo or you did a modification on your installation? First time looking at a HA addon but i think config.yaml is indeed where the magix should happen. Can you send a merge request if you successfully did it?

Its possible I forked this repo and made it possible. frenck already had another Issue with that and moved it to the Discussions tab.

**Comment by Salvora** [comment]
bump
