### ISSUE TITLE
How to add environment variables in this add-on

### ISSUE THREAD

**Issue by gx19970920** [hassio-addons/addon-bitwarden#308]
# Problem/Motivation

> How to add environment variables in this add-on

## Expected behavior

> I want to add environment variables' YUBICO-CLIENT-ID 'and' YUBICO-SECRET_KEY ', but after filling them out, the log shows that these two environment variables have not been set. How can I add custom environment variables correctly
![image](https://github.com/hassio-addons/addon-bitwarden/assets/33535925/9ddf568d-d136-4d33-90d6-4de28f6b72b2)
## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> How to add environment variables in this add-on

You cannot, there is no such option.

../Frenck

**Comment by gx19970920** [comment]
Thank you for your reply, but when I set up yubiko hardware key verification in Bitgarden, I was prompted that the corresponding environment variable was not added, and the log also showed that 'YUBICO CLIENT ID' and 'YUBICO SECRET_KEY' could be added

bitwarden nterface：
![image](https://github.com/hassio-addons/addon-bitwarden/assets/33535925/aa45bc13-edac-4dc4-8d41-8de990c1f2eb)

add-on log：
![image](https://github.com/hassio-addons/addon-bitwarden/assets/33535925/777c9299-f6d7-4713-90ac-f4d33f473e39)

**Comment by frenck** [comment]
Use the admin panel, as documented in the add-on documentation.

../Frenck
