### ISSUE TITLE
Release v0.23

### ISSUE THREAD

**Issue by Venefilyn** [hassio-addons/addon-bitwarden#314]
I saw that you updated the images but never made a release for it, could this be done soon-ish as the release tackles 3 CVEs?

**Comment by frenck** [comment]
Merged in #312

**Comment by Venefilyn** [comment]
@frenck right but the tag and release was never done :D

**Comment by frenck** [comment]
Neither has testing yet, hence it isn't shipped. Issue has been resolved on dev.

**Comment by bilogic** [comment]
Thanks, really looking forward to the release

Now... if only HA has an insider/canary channel for add ons... haha

**Comment by jdeath** [comment]
Any update on a release?

**Comment by Venefilyn** [comment]
@frenck can we open this issue until a release has been made?
