### ISSUE TITLE
Cryptography error

### ISSUE THREAD

**Issue by AbeltjeNL** [hassio-addons/addon-bitwarden#316]
The latest version of the BW iOS app shows the following error after successful login:

```Cryptography error, The cipher's MAC doesn't match the expected value ```

When I search this error i found:
https://github.com/dani-garcia/vaultwarden/issues/4775

Looks like RBW is the culprit:
https://github.com/NixOS/nixpkgs/pull/333147

There also is a new version of the server available: v1.32.0.

In: 
https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.0

Seems to be the fix: 
https://github.com/dani-garcia/vaultwarden/pull/4800

Can @frenck look in to this when time is available?

Edit: after restoring a backup the database is reachable without errors. After login with the iOS app the database is broken again. After a nother restore and installing the beta iOS app everything is working again:

https://bitwarden.com/blog/native-mobile-apps/

Do not make new entries until this is resolved. If you make new entries the database will brake again!

**Comment by SpawnSP2** [comment]
Do you know if updating the server it will fix a broken database? My last backup is from May 😱
Maybe i’ll try with an independent updated instalation on Docker and copying the data folder from the HA component. For me, it’s quite urgent. But yeah, my fault for not making more frequent backups.

**Comment by AbeltjeNL** [comment]
> Do you know if updating the server it will fix a broken database? My last backup is from May 😱
> 
> Maybe i’ll try with an independent updated instalation on Docker and copying the data folder from the HA component. For me, it’s quite urgent. But yeah, my fault for not making more frequent backups.

Don't know.. My hope is that the updated version will fix a broken database but we will have to give it a try when the updates version is published.

**Comment by AbeltjeNL** [comment]
I think there is something good incomming:

https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.1

**Comment by AbeltjeNL** [comment]
The latest version of the addon seems to do the trick and fixes the issue(s). Tested with normal and beta iOS apps. Leaving this open for a couple of days to be sure

**Comment by frenck** [comment]
It is fixed 👍 

../Frenck
