### ISSUE TITLE
Expose /data directory

### ISSUE THREAD

**Issue by LostSoulfly** [hassio-addons/addon-bitwarden#32]
# Problem/Motivation

I currently run bitwarden_rs on a different server and would like to use this as a backup/emergency server. I would like to automatically sync my db.sqlite3, config.json, and RSA key files between the servers so that I will always have a server available. The failover is out of scope of this addon, but it will be handled either by my current HTTPS reverse proxy automatically, or I'll make the change manually.

## Proposed changes

Ideally, the bitwarden_rs /data directory could be exposed as a folder to the default /addons directory exposed through the hassio Samba share.

This would allow me to sync my vault as well as offer others the ability to manually backup their bitwarden_rs data for safe keeping. I don't believe there is any security implications as everything is well encrypted, but perhaps this could be a config option for those that choose not to do it.  

I believe I could use Portainer to map it manually but doing it each time there is an upgrade would be challenging. And using this addon without the ability to make a manual backup for safekeeping worries me, so I don't know that I could use it as a primary server (or recommend it to others) until it's possible.

**Comment by frenck** [comment]
We can't expose the data directory.

As a workaround, download a snapshot and extract it (it is a zip format).
