### ISSUE TITLE
New CVE 

### ISSUE THREAD

**Issue by dm82m** [hassio-addons/addon-bitwarden#335]
# Problem

there is a critical cve reported and fixed: https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.7

## Proposed changes

Update to the latest version.

maybe you could upgrade it @frenck , much appreciated.

**Comment by dm82m** [comment]
Renovate already updated, so only the release is open: https://github.com/hassio-addons/addon-bitwarden/commit/47b6562677e7c6ade5dd44b36a53acf0e4cf446a

**Comment by sinclairpaul** [comment]
Adding the details of the workarounds, which likely already apply to the majority of users.

Workarounds
If it's not possible to update to 1.32.7, some possible workarounds are:

Disabling ORG_GROUPS_ENABLED, which would disable groups functionality on the server.
Disabling SIGNUPS_ALLOWED, which would not allow an attacker to create new accounts on the server.

**Comment by frenck** [comment]
https://github.com/hassio-addons/addon-bitwarden/releases/tag/v0.23.7
