### ISSUE TITLE
Disable user registration?

### ISSUE THREAD

**Issue by JulienTant** [hassio-addons/addon-bitwarden#36]
# Problem/Motivation

I noticed that there is a way to disable user registration with bitwared_rs by using the environment variable : `SIGNUPS_ALLOWED=false` - i cannot seem to find if I can put that somewhere

## Expected behavior

N/A

## Actual behavior

N/A

## Steps to reproduce

N/A

## Proposed changes

Offer a way to disable user registration.

**Comment by frenck** [comment]
It is available in the admin panel on the `/admin` url.
