### ISSUE TITLE
Android app complaining about TLS handshake when SSL enabled

### ISSUE THREAD

**Issue by JohnnySSH** [hassio-addons/addon-bitwarden#37]
# Problem/Motivation
The Bitwarden Android app complains with an error message when attempting to login. As a result it is unable to login to Bitwarden running as a Hassio app.

> (Why the issue was filed)

## Expected behavior
The App should be able to login
> (What you expected to happen)

## Actual behavior

An error has occurred
Exception message: Handshake failed

> (What actually happened)

## Steps to reproduce
Install the Let's Encrypt app and generate a certificate using a Full Qualified Domain Name

Configure Bitwarden to use the new fqdn and HTTPS protocol with Let's Encrypt cert

Point the app to the FQDN using: https://fqdn:7277

> (How can someone else make/see it happen)

## Proposed changes

I am not sure where the problem lies specifically but as Hassio uses a reverse Nginx proxy to proxy the secure ssl information to apps behind it, it seems like a possible cause.
Currently TLSv1.2 and TLSv1.3 is enabled by default in the proxy config. I attempted to add TLSv1.0 and TLSv1.1 but with no success.

I wonder if it has something to do with the ssl ciphers? 

I have checked the certificate in addition using many different tools and everything looks good, browsers also do not complain either so the certificates seem to be fine.

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The android app works fine for me.

Does the web vault open successfully from a browser on the same device?  Not knowing how you have name resolution configured, but please consider Android devices tend to prefer Google's DNS servers.

**Comment by JohnnySSH** [comment]
Yes the browser opens up the vault fine on the same devices. The issue is only when using SSL set to on. I have 2x public dns servers to host my domain so DNS isn't an issue.

The actual error message of: Handshake Failed is odd!

Initially I thought it might be an intermediary certificate issue that perhaps wasn't supplied with Lets Encrypt, however I checked this out and it is fine.

From the error message given I can only assume it has something to do with the app not being able to establish a secure link.....

**Comment by sinclairpaul** [comment]
I think the best place to look at the issue would be at https://github.com/dani-garcia/bitwarden_rs

The addon wraps the existing app/software.

**Comment by JohnnySSH** [comment]
Thanks. I'll try over there and see what happens. In the history of the app I have read reports of there being an issue with the TLS version in the Nginx proxy. That seemed to be fixed however.

**Comment by JohnnySSH** [comment]
Just quickly, we have established that the TLS version being negotiated is v1.0.

Where is the config file for ssl proxy configuration for Bitwarden?

Currently I'm looking at this file:
/usr/share/hassio/addons/core/nginx_proxy/data/nginx.conf

I made the following change:

    server {
        server_name %%DOMAIN%%;

        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        ssl_certificate /ssl/%%FULLCHAIN%%;
        ssl_certificate_key /ssl/%%PRIVKEY%%;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;

which didn't seem to help.

**Comment by sinclairpaul** [comment]
The nginx configuration is held within the container, its not something you can just edit on disk.

If your device is negotiating 1.0/1.1 I would suggest there is a bigger issue, as these are essentially end of life and not supported.  The mobile app supports 1.2.

Is the connection external or internal?, is there something else between your device and the server that could be causing this?

**Comment by JohnnySSH** [comment]
The thing is, I have 3 devices and all of them seem to be doing the same thing; as in negotiating TLSv1.0. 2 of them are Android 7 devices and 1 is running Android 10 or 11.

The connection is internal and nothing should be in the way which alters the TLS version.

On the upstream Bitwarden project I was told that my BW version is slightly out of date... I don't know if this is the issue? Though I told HomeAssistant to 'auto update' the apps.

I'm not sure where to start digging now, especially since you say that I can't alter the Nginx config.

**Comment by JohnnySSH** [comment]
Just updated my upstream bug report.

I have checked my server using: https://www.digicert.com/help/

The response is as follows:

Protocol Support
TLSv1.2
TLSv1.3

TLS ciphers supported by the server
TLSv1.2
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

TLSv1.3
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_GCM_SHA256


So if the server supports TLS 1.2 and 1.3 then it must be a client issue????

Wireshark is reporting that it tries v1.2 first then goes down to 1.1 and 1.0. At this point I'll wait for what upstream suggests as it might be an app issue not supporting the ciphers or something.....

**Comment by sinclairpaul** [comment]
Not sure I follow here, as you mentioned you were connecting internally, but have validated externally?

Do you use Cloudflare or any other proxy type service?, if you point the app directly to the internal IP over https, do you get a cert mismatch error (would would suggest to me that it has negotiated correctly).

**Comment by JohnnySSH** [comment]
Sorry for the confusion :-( 

My Hassio instance is locally hosted on a server in my network. I am attempting to connect with my client which is also within my local network. Since I have public facing servers tied to static IP addresses, I opened up port 443 on my firewall and used PAT (port address translation) to redirect the incoming HTTPS check for the test *only*, to local port 7277 which is where BW is.

So the access method (external or internal) is really irrelevant as it's the Android app which is not able to connect, whether internally or externally (which I have additionally tested during the certificate test).

Now I have closed the port again on the firewall for external access. (just for clarification)

So really the issue is the app not being able to negotiate a valid TLS method with the Nginx proxy.

This is what is really making me bang my head against the wall now as where does the problem lie? Android app or Nginx?

**Comment by sinclairpaul** [comment]
The app supports and works with TLS1.2, personally I use it, and we haven't seen previous issues logged on this.

Although you mention the external/internal access method is irrelevant, please consider my earlier comment on how Android devices will prefer Google DNS servers.  I don't know how you are providing name resolution internally (I will assume some form of split DNS), but this should be considered. 

Nginx is providing TLS 1.2/1.3, at this point I think it is fair to say that there is nothing in the addon configuration that is causing the issue, so for now I will close this out (I believe vault access from the web browser works ok from the same device).

I would recommend jumping on Discord for any help with further troubleshooting.

**Comment by JohnnySSH** [comment]
No problem.

The DNS is provided locally through dhcp, which points to my local name servers.

Yep you are correct that it's split dns with internal/external zones.

Thanks for trying to help!

**Comment by JohnnySSH** [comment]
Just want to add something quickly....

I have just successfully logged in using an old Android tablet (Google Nexus 7) which runs Android 6.

The issue seems to be related to the Samsung Galaxy S6 phones and/or Android 7 it seems......

I'll keep digging! I knew it wasn't a DNS'ing issue as these devices are on the same subnet using the same internal DNS servers.
