### ISSUE TITLE
Unknown error when using mail function

### ISSUE THREAD

**Issue by Jeltel** [hassio-addons/addon-bitwarden#4]
# Problem/Motivation
I'm trying to invite new users and also adding users to my orginisation. Both function require a mail to be sent.
So i've configured a smtp server (which is operational), but I can't test the integration.

## Expected behavior
I expect the bitwarden application to sent a mail to the email address entered.

## Actual behavior
No mail is sent (nothing seen in the smpt server) and the interface returns an Unknown Error.
It does note the mail address as invited.
In the log it says the following when inviting a user:
```
[2019-08-16 22:00:54][rocket::rocket][INFO] POST /admin/invite/ application/json:
[2019-08-16 22:00:54][_][INFO] Matched: POST /admin/invite (invite_user)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: StringError("failed to lookup address information: Temporary failure in name resolution") })', src/libcore/result.rs:999:5
```
And when (re-)inviting a user to the organisation:
```
[2019-08-16 22:10:00][_][INFO] Matched: POST /api/organizations/<org_id>/users/<user_org>/reinvite (reinvite_user)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: StringError("failed to lookup address information: Temporary failure in name resolution") })', src/libcore/result.rs:999:5
```
So same error. Some name resolution thing. When it is strange that other application (my mail server itself, can sent mails via the same smtp

## Steps to reproduce
Adding a smtp server configuration the bitwarden vault and then inviting a user.

**Comment by Jeltel** [comment]
Or is this just a strange way of saying my smtp configuration is wrong?

**Comment by sinclairpaul** [comment]
What did you specify for the SMTP server, can it be resolved by the addon?

**Comment by Jeltel** [comment]
SMTP.sendgrid.net

And how can I check if the add-on can resolve that?

**Comment by frenck** [comment]
"Temporary failure in name resolution" looks like a DNS issue to me...

**Comment by Jeltel** [comment]
The machine on which hassio and bitwarden are running can ping SMTP.sendgrid.net.

But I also cannot see any icons. So maybe there is some nameresolving issue.

**Comment by frenck** [comment]
The host is not relevant in this case. The error message is clear, it cannot resolve the given fqdn.

**Comment by Jeltel** [comment]
Ok, how can I check from inside bitwarden. Can I use docker-exec?

**Comment by Jeltel** [comment]
Ok, changed to an internal smtp relay server and now it does work. Strange. Because other devices on my network can connect directly to sendgrid.

Then the issue is the generated error. It shouldn't say unknown error in the interface.

**Comment by frenck** [comment]
That is not in control of this add-on, add-ons wrap existing software.
