### ISSUE TITLE
Is it possible to add fail2ban?

### ISSUE THREAD

**Issue by N1c093** [hassio-addons/addon-bitwarden#41]
# Problem/Motivation

Is it possible that fail2ban or something similar will be implemented to prevent brute force attacks? Bitwarden RS recommend to implement it: https://github.com/dani-garcia/bitwarden_rs/wiki/Fail2Ban-Setup

Currently no ip address will be banned

## Expected behavior

Ban ip-address, if there are to much wrong login attempts 

## Actual behavior

Brute force is possible, no ip address will be banned

## Steps to reproduce

Type in the wrong password a lot of times.

## Proposed changes

Implement fail2ban or something else to prevent brute force attacks

**Comment by frenck** [comment]
Sorry, that is not possible. Feel free to create your own version or setup in case you like those things.

**Comment by N1c093** [comment]
Thanks for your feedback. 
I already thought that this wouldn't be possible.
