### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Metal-Frog** [hassio-addons/addon-bitwarden#42]
# Problem/Motivation

Hi, I've installed the addon. It is running but I cannot access the UI. The log is completely empty.
Any ideas?

Regards, Tom

## Expected behavior

UI

## Actual behavior

Nothing

## Steps to reproduce

Just installed and started it.
(also restarted PI)

**Comment by Metal-Frog** [comment]
I've added `log_level: debug` to the config.
After a while the following line appeared:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.`

**Comment by damanti-me** [comment]
can you go one level of logging further? trace?

**Comment by sinclairpaul** [comment]
I would guess a better bet would be to look at the supervisor logs.

**Comment by Metal-Frog** [comment]
Got it working.
The problem was that SSL has been set to true but no certificate files were present.
Furthermore it takes really long until the addon is completely started - I haven't been patient enough :).
But a few times the settings were corret but the addin wasn't starting anyway ...
