### ISSUE TITLE
Cannot open attachments 

### ISSUE THREAD

**Issue by mironalessandro** [hassio-addons/addon-bitwarden#46]
# Problem/Motivation

> Cannot open Attachments

## Expected behavior

> Open Attachments 

## Actual behavior

> An error when I try from iOS App and continuous loading from website 

## Steps to reproduce

> Upload an attachment and try to open it. I try with identities and with login but i have the same issue. I try with PDF and also with images. I try to upload the file from web and also from iOS but i have the same issue.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mironalessandro** [comment]
@frenck can you give an update on this?

**Comment by frenck** [comment]
Yes

No updates

**Comment by mironalessandro** [comment]
Ok, thanks.

**Comment by mironalessandro** [comment]
The problem is still there

**Comment by frenck** [comment]
This should be fixed with v0.7.0:

<https://github.com/hassio-addons/addon-bitwarden/releases/tag/v0.7.0>

Could you test this?

**Comment by mironalessandro** [comment]
Yes absolutely.. When I have the update I can test it

**Comment by mironalessandro** [comment]
Nothing change on the new version 😔 ... Same issue with attachments and login after disconnection

**Comment by frenck** [comment]
Thanks for letting me know!

**Comment by shirou93** [comment]
@frenck hi, error disaapear when put correct domain in admin panel (default http://localhost).

I have different erro. When try upload attachment bigger than 10mb i have error.

**Comment by mironalessandro** [comment]
>  @mironalessandro hi, error disaapear when put correct domain in admin panel (default http://localhost). Can you check and confim?
> 
> 
> 
> I have different error. When try upload attachment bigger than 10mb i have error.
> 
> 
> 
> log `2021/02/15 08:47:14 [error] 411#411: *336 client intended to send too large body: 13142859 bytes`
> 
> 
> 
> this is  propbaly nginx config issue: 
> 
> 
> 
> `client_max_body_size 10M;` is default i see in config file is 4G (maybe this config was ignored?)
> 
> 
> 
> @frenck can you check it? (bitwarden docummentation says An individual file attachment must be 100MB or smaller. )
> 
> 
> 
> I think disable check max body size via 0 it's fine. Bitwarden check size file to max 100mb.
> 
> 
> 
> Thanks

Hi! 

I don't understand what do you mean with try with local host...

**Comment by shirou93** [comment]
> > @mironalessandro hi, error disaapear when put correct domain in admin panel (default http://localhost). Can you check and confim?
> > I have different error. When try upload attachment bigger than 10mb i have error.
> > log `2021/02/15 08:47:14 [error] 411#411: *336 client intended to send too large body: 13142859 bytes`
> > this is  propbaly nginx config issue:
> > `client_max_body_size 10M;` is default i see in config file is 4G (maybe this config was ignored?)
> > @frenck can you check it? (bitwarden docummentation says An individual file attachment must be 100MB or smaller. )
> > I think disable check max body size via 0 it's fine. Bitwarden check size file to max 100mb.
> > Thanks
> 
> Hi!
> 
> I don't understand what do you mean with try with local host...

In admin panel you must add correct domain or IP adress your server with https example https://192.168.1.5/.

**Comment by mironalessandro** [comment]
> > > @mironalessandro hi, error disaapear when put correct domain in admin panel (default http://localhost). Can you check and confim?
> > > I have different error. When try upload attachment bigger than 10mb i have error.
> > > log `2021/02/15 08:47:14 [error] 411#411: *336 client intended to send too large body: 13142859 bytes`
> > > this is  propbaly nginx config issue:
> > > `client_max_body_size 10M;` is default i see in config file is 4G (maybe this config was ignored?)
> > > @frenck can you check it? (bitwarden docummentation says An individual file attachment must be 100MB or smaller. )
> > > I think disable check max body size via 0 it's fine. Bitwarden check size file to max 100mb.
> > > Thanks
> > 
> > 
> > Hi!
> > I don't understand what do you mean with try with local host...
> 
> In admin panel you must add correct domain or IP adress your server with https example https://192.168.1.5/.

I try it... and now only from ios works well... from chrome and edge extension still not working... anyway i try an attachment with  27mb and i have an error like you ... for me is not important this but just to add a new test for franck

**Comment by shirou93** [comment]
> > > > @mironalessandro hi, error disaapear when put correct domain in admin panel (default http://localhost). Can you check and confim?
> > > > I have different error. When try upload attachment bigger than 10mb i have error.
> > > > log `2021/02/15 08:47:14 [error] 411#411: *336 client intended to send too large body: 13142859 bytes`
> > > > this is  propbaly nginx config issue:
> > > > `client_max_body_size 10M;` is default i see in config file is 4G (maybe this config was ignored?)
> > > > @frenck can you check it? (bitwarden docummentation says An individual file attachment must be 100MB or smaller. )
> > > > I think disable check max body size via 0 it's fine. Bitwarden check size file to max 100mb.
> > > > Thanks
> > > 
> > > 
> > > Hi!
> > > I don't understand what do you mean with try with local host...
> > 
> > 
> > In admin panel you must add correct domain or IP adress your server with https example https://192.168.1.5/.
> 
> I try it... and now only from ios works well... from chrome and edge extension still not working... anyway i try an attachment with 27mb and i have an error like you ... for me is not important this but just to add a new test for franck

For me extensions in web browsers work well. Only attachments bigger than 10 mb show errors.
