### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by mattbruman** [hassio-addons/addon-bitwarden#51]
No updates in 6 months, for a product that secures passwords this seems dangerous to keep running without updates.

**Comment by frenck** [comment]
Nope.

**Comment by colinfrei** [comment]
I think it's not so much abandoned as dependent on a single person that has other priorities.

But yeah, for such a sensitive product, that's a big risk.

**Comment by frenck** [comment]
Locked the topic. Feel free to discuss this on the forums or discord chat. I like to track issues on GitHub. Thanks 👍
