### ISSUE TITLE
docker image not available

### ISSUE THREAD

**Issue by jasonehines** [hassio-addons/addon-bitwarden#53]
My bitwarden wasn't working after upgrading to the latest from 0.116. I"m running the Supervisor version, so I tried to manually pull homeassistant/armv7-addon-bitwarden but it's not available.

**Comment by jasonehines** [comment]
I used the ha comand line tool to try and start the addons and it gives me a 404. But I was able to use the output to get the correct version and do a manual pull from the host. Once I did that I was able to start them.

**Comment by frenck** [comment]
Manually controlling and managing your Docker is not support on a supervisor system.
Not sure on your issue from that standpoint either.
