### ISSUE TITLE
Wrong master password on desktop client (firefox / chrome / edge)

### ISSUE THREAD

**Issue by nopzolder** [hassio-addons/addon-bitwarden#54]
# Problem/Motivation

Since the last update of the addon there are issue with unlocking bitwarden_rs in the browser

## Expected behavior

Logging in without issue

## Actual behavior

Error: Invalid master password

## Steps to reproduce

Just try to unlock the plugin in the browser, enter your correct password and watch the error

## Proposed changes

Update the bitwarden_rs addon at leas to version 1.16.2 ->  https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.16.2
This issue is fixed in that release: Fixed issue unlocking vault in the desktop client.

**Comment by osxdoc** [comment]
I have the same Problem.

**Comment by Nailik** [comment]
This is due to the version of the docker image and your client. You have to logout and login again.
https://github.com/bitwarden/mobile/issues/1125

**Comment by nopzolder** [comment]
> 
> 
> This is due to the version of the docker image and your client. You have to logout and login again.
> [bitwarden/mobile#1125](https://github.com/bitwarden/mobile/issues/1125)

That is a workaround, not the solution, the solution is to upgrade to docker container to the lastest version. I tested it with a container outside Home Assistant and then it's working like it should.

**Comment by osxdoc** [comment]
It looks like the hassio-addons/addon-bitwarden in broken at the moment, it doesn't work with the Desktop clients and the Android App.

**Comment by Nailik** [comment]
Jeah exactly what i meant there is only a workaround.

**Comment by Arcon389** [comment]
Same prolem here. I hope there will be a new version release soon!

**Comment by marti28** [comment]
Same issue here as well. Happy to help testing if required.

**Comment by switchbert** [comment]
I do have the ame issue. My improper workaround is to unlock it with the PIN code in all desktop clients.

**Comment by dave-castle** [comment]
will this gonne be fixed? Tried to setup within Docker on my Synology and failed to get HTTPS running :(

**Comment by frenck** [comment]
yes it will be fixed. The project is currently migrating to a new deployment process that allows for this.

PS: Synology is not a supported platform at all, so... Yeah 🤷

**Comment by Nailik** [comment]
> yes it will be fixed. The project is currently migrating to a new deployment process that allows for this.
> 
> PS: Synology is not a supported platform at all, so... Yeah 🤷

I think he meant he can't get the "pure" Bitwarden Server running on Docker with https.

**Comment by dave-castle** [comment]
> yes it will be fixed. The project is currently migrating to a new deployment process that allows for this.
> 
> PS: Synology is not a supported platform at all, so... Yeah 🤷

Cool, want to migrate from 1password to set hosted bitwarden. Thanks for your efforts @frenck 

@Nailik yes, you got it 😜

**Comment by nopzolder** [comment]
> 
> 
> yes it will be fixed. The project is currently migrating to a new deployment process that allows for this.
> 
I appreciate your effort, thx Frenck!

**Comment by damanti-me** [comment]
> > yes it will be fixed. The project is currently migrating to a new deployment process that allows for this.
> 
> > 
> 
> > PS: Synology is not a supported platform at all, so... Yeah 🤷
> 
> 
> 
> I think he meant he can't get the "pure" Bitwarden Server running on Docker with https. 

I'm also using docker on Synology in the meantime. This is an issue for several months now.

**Comment by dave-castle** [comment]
> > > yes it will be fixed. The project is currently migrating to a new deployment process that allows for this.
> > 
> > 
> > > 
> > 
> > 
> > > PS: Synology is not a supported platform at all, so... Yeah 🤷
> > 
> > 
> > I think he meant he can't get the "pure" Bitwarden Server running on Docker with https.
> 
> I'm also using docker on Synology in the meantime. This is an issue for several months now.

How do you got HTTPS working?

**Comment by damanti-me** [comment]
I'm using frencks reverse proxy's add on to access behind my NAT. There  are also some nice instructions [https://www.kartolo.de/2020/02/03/installing-bitwarden-on-synology-diskstation/](online)

**Comment by frenck** [comment]
This is fixed in v0.7.0 of the add-on.

<https://github.com/hassio-addons/addon-bitwarden/releases/tag/v0.7.0>
