### ISSUE TITLE
Questions about the releases

### ISSUE THREAD

**Issue by niekniek89** [hassio-addons/addon-bitwarden#55]
# Problem/Motivation/Question:

Hello,

I have a question about the releases (apart from that I am super satisfied with the app), but I see that it is already 7 versions behind ... is that correct?

is there any way to update this?
I am on version 2.13.2, and see that 2.17.1 is out.

**Comment by frenck** [comment]
See all other issue and PR.

It needs work, feel free to help out and do it.
