### ISSUE TITLE
change multi-arch build workflow

### ISSUE THREAD

**Issue by fcrisciani** [hassio-addons/addon-bitwarden#57]
# Problem/Motivation
Currently the version cannot be upgraded because because of the way multiarch got introduced by bitwarden and the way the build of this addon is done.
Example of the failure signature from last ci results:
```
manifest for bitwardenrs/server:1.16.0-aarch64 not found: manifest unknown: manifest unknown
```

## Proposed changes
Franck do you think migrating to use buildx with dind (docker in docker) as described in https://www.docker.com/blog/multi-arch-build-what-about-gitlab-ci/ is a viable solution?

I noticed that there is already some configuration in https://github.com/hassio-addons/organization/blob/master/gitlabci/addon.yml#L65-L73 that mentions dind is it possible to fetch buildx and change the build step (https://github.com/jdrouet/docker-on-ci/blob/master/Makefile#L7-L9)?

**Comment by frenck** [comment]
We already use a DIND on native platforms. I'll be switching away from GitLab CI completely in the upcoming weeks.
