### ISSUE TITLE
Update to latest?

### ISSUE THREAD

**Issue by barrymossel** [hassio-addons/addon-bitwarden#72]
# Problem/Motivation

Chrome extension locks. Unlocking is not possible with master password (error occured). Logging out and logging in works though with exactly the same password. Apparantly updating docker fixes the problem: https://www.reddit.com/r/Bitwarden/comments/jzs1hx/cant_unlock_my_vault_but_can_logout_and_back_in/

## Expected behavior

Unlock 

## Actual behavior

Doesn't unlock and message appears: error occured.

## Steps to reproduce

Let extension lock and try to unlock.

## Proposed changes

Update docker to latest version?

**Comment by frenck** [comment]
It is already on the latest...
