### ISSUE TITLE
Add optional environment variables at startup

### ISSUE THREAD

**Issue by fliphess** [hassio-addons/addon-bitwarden#73]
Hi! I'd like to be able to change some environment variables at startup and I was wondering if said functionality would be appreciated when offered as a PR.

Preferably I add a list of env vars that can be set in the configuration as is done in (for example) the [grafana addon](https://github.com/hassio-addons/addon-grafana/blob/main/grafana/config.json#L16). 

When I add this feature to the addon, would you merge it or is it something I'd better use just in my own fork?

**Comment by frenck** [comment]
Those aren't needed, as the admin panel offers access to all features via a UI directly.
