### ISSUE TITLE
Cannot use weak password report

### ISSUE THREAD

**Issue by AlexKnowsIt** [hassio-addons/addon-bitwarden#77]
# Problem/Motivation

In the tools section of bitwarden I can't click on the weak password report without the website crashing. All other tools on this site (reused passwords, etc.) work totally fine, just this feature seem to break in my browser. The site will hang there until I close it, all other buttons on the website aren't working either from that moment on until reopening the page.

## Steps to reproduce

I am using Firefox 84.0.2 and run the current version 0.7.0 of this addon.

## Proposed changes

I don't really know why this is happening because I am also running another Bitwarden instance seperatly with the current Docker image from Docker Hub and there isn't this problem.

**Comment by frenck** [comment]
Anything in your browser log? add-on log? Supervisor logs?

**Comment by AlexKnowsIt** [comment]
Sadly no. In the browser log as well as in the add-on log there is no occurence of this event at all (not even a error message or that it requested the page to load). The browser will just stop working and tell that the page stopped responding. The only interesting information from the supervisor to me was that it didn't restart the addon so it seems to be a problem on the webpage , not something that would make the addon itself crash.

**Comment by frenck** [comment]
Alright, as a Firefox user, this is probably not a fun question, but...

Does it work in Chrome? 😉

**Comment by AlexKnowsIt** [comment]
Well played ;)
I just downloaded Chrome and tried it out but its exactly the same behaviour. All tools are working except the weak password report.

**Comment by AlexKnowsIt** [comment]
So my configuration did not change and I tried it last week with 3 different devices and had on all of them the same problem, but I just tried it again and it seems to work now. So sadly I don't know what the problem was (maybe it took just some time to proccess the passwords), but it seems to be fixed.

**Comment by frenck** [comment]
Uh, that's weird? I haven't had the time yet to followup/test/reproduce. But I'm leaving it on my list to try it at least once

**Comment by frenck** [comment]
🤷 Could not get it to break
