### ISSUE TITLE
How to setup STMP server?

### ISSUE THREAD

**Issue by stphndrnd** [hassio-addons/addon-bitwarden#80]
# Problem/Motivation
Be able to set SMTP server to send invite to users

## Expected behavior
A mail to be sent to users

## Actual behavior
Could not find where to setup the SMTP server parameters as per https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration - Where are those?

## Steps to reproduce
See above

## Proposed changes
See above

**Comment by AlexKnowsIt** [comment]
You can set them up using the bitwarden admin panel. Its all explained in the documentation under installation .
