### ISSUE TITLE
Add optional environment

### ISSUE THREAD

**Issue by niekniek89** [hassio-addons/addon-bitwarden#95]
Hi,

it is possible to specify these variables:

SIGNUPS_ALLOWED	**false**

I have bitwarden open to the outside.
but now anyone can create bitwarden vaults.

this is no longer possible with these variables.
no idea if this is possible.

**Comment by sinclairpaul** [comment]
Duplicate of #36 

Use the admin panel

**Comment by niekniek89** [comment]
thank you very much. it worked.
