### ISSUE TITLE
Unable to change settings that need email verification

### ISSUE THREAD

**Issue by Bodge-IT** [hassio-addons/addon-bitwarden#98]
# Problem/Motivation

I cannot send emails from Bitwarden as these params are unavailable in the addon

## Expected behavior

Have a verification email be sent from Bitwarden when changing email for example

## Actual behavior

No email sent, email is not configured for the Bitwarden server

## Steps to reproduce

Try changing email in settings

## Proposed changes

Open up server to json config form for main params

**Comment by frenck** [comment]
tried the admin panel?

**Comment by Bodge-IT** [comment]
Do you mean Admin on Bitwarden?  Of course.  Settings not available there either.
It says on this page that settings need to be applied at run time:
https://bitwarden.com/help/article/environment-variables/

**Comment by Bodge-IT** [comment]
Sry, this page:
https://bitwarden.com/help/article/install-on-premise/

;-) Been doing a bit of digging

**Comment by frenck** [comment]
This is Bitwarden RS, not bitwarden.

**Comment by frenck** [comment]
See: https://github.com/hassio-addons/addon-bitwarden/blob/main/bitwarden/DOCS.md#installation

Step 5.

**Comment by Bodge-IT** [comment]
Boom and just like that he opens a magic doorway!  I'll get busy. Thanks.
